language: python # Set the build language to Python

python: 3.6 # Set the version of Python to use

branches: master # Set the branch to build from

install:
    - pip install mkdocs # Install the required dependencies

script: true # Skip script (Don't use this if one already exists)

before_deploy:
    - mkdocs build --verbose --clean --strict # Build a local version of the docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $ACCESS_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: site
  on:
    branch: master