language: python
python: 3.6
branches: master
install:
- pip install mkdocs
script: true
before_deploy: - mkdocs build --verbose --clean --strict # Build a local version of the docs
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: site
 on:
   branch: master
